version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.8.0

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - cache-{{ checksum "requirements.txt" }}
            - cache-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          paths:
            - venv
          key: cache-{{ checksum "requirements.txt" }}

      # run tests!
      - run:
          name: syntax tests
          command: |
            . venv/bin/activate
            python -m compileall bot.py cogs  -fq
      - store_artifacts:
          path: test-reports
          destination: test-reports